### PR TITLE
New cards

### PR DESCRIPTION
**Pull request by kushieda-minori**
* updates format to be automated output
* adds new/missing cards

### CODE REVIEW

**Comment by aister** [comment]
wat's wrong?

**Comment by kushieda-minori** [comment]
looks like another bot is being used now. so we won't need this update, at least in the 2 chats I know use the bot for VC

**Comment by aister** [comment]
make sure those bots are not using this file lol

**Comment by kushieda-minori** [comment]
the other bot author did a clone first, so they are out of sync now. Thanks!

**Comment by aister** [comment]
ok then I can delete this file and remove VC commands on the bot, thanks for informing me 👍

**Pull request closed without merging**
